"""Add poster column to movies

Revision ID: 7840ed357f4a
Revises: 24d13563d916
Create Date: 2025-09-25 15:34:31.446863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7840ed357f4a'
down_revision = '24d13563d916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=255), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
